---
resources:
  - ../base
patches:
  - target:
      kind: PersistentVolumeClaim
      name: busybox-pvc-rbd-1
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: rook-ceph-block
      - op: replace
        path: /metadata/labels/consistency-group
        value: cg-rbd
  - target:
      kind: PersistentVolumeClaim
      name: busybox-pvc-rbd-2
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: rook-ceph-block
      - op: replace
        path: /metadata/labels/consistency-group
        value: cg-rbd
  - target:
      kind: PersistentVolumeClaim
      name: busybox-pvc-rbd-3
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: rook-ceph-block
      - op: replace
        path: /metadata/labels/consistency-group
        value: cg-rbd
  - target:
      kind: PersistentVolumeClaim
      name: busybox-pvc-cephfs-1
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: rook-cephfs
      - op: replace
        path: /metadata/labels/consistency-group
        value: cg-cephfs
  - target:
      kind: PersistentVolumeClaim
      name: busybox-pvc-cephfs-2
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: rook-cephfs
      - op: replace
        path: /metadata/labels/consistency-group
        value: cg-cephfs
  - target:
      kind: PersistentVolumeClaim
      name: busybox-pvc-cephfs-3
    patch: |-
      - op: replace
        path: /spec/storageClassName
        value: rook-cephfs
      - op: replace
        path: /metadata/labels/consistency-group
        value: cg-cephfs
